name: vidyakunj_attendance
description: Attendance app for Vidyakunj School Navsari
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.14.0
  sqflite: ^2.2.0+1
  path_provider: ^2.0.12
  file_picker: ^5.2.4
  excel: ^2.0.1
  provider: ^6.0.5
  connectivity_plus: ^4.0.0
  flutter_secure_storage: ^8.0.0
  fluttertoast: ^8.2.1
flutter:
  uses-material-design: true
